## Making PyTorch easy to use: a more intuitive approach to deep learning

### Can do everything in NumPy (nd arrays) but with PyTorch tensors

In [2]:
import torch


In [3]:
## basic operations

x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
x = torch.arange(0,3, step = 0.2)
x

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000])

In [6]:
x = torch.FloatTensor(2, 3)
x

tensor([[1.4013e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [19]:
x = torch.rand(5,3)
out = torch.index_select(x, 0, torch.LongTensor([0,0]))
print(x)

tensor([[0.3603, 0.0832, 0.6640],
        [0.7721, 0.0199, 0.0444],
        [0.2913, 0.9217, 0.9616],
        [0.3593, 0.3893, 0.5650],
        [0.8964, 0.9852, 0.6519]])


In [23]:
## array indexing

x[:,2], x[1:,2]

(tensor([0.6640, 0.0444, 0.9616, 0.5650, 0.6519]),
 tensor([0.0444, 0.9616, 0.5650, 0.6519]))

In [27]:
## selection by masking

x = torch.randn(3,3)
mask = torch.ByteTensor([[1,0,0],[0,1,0], [0,0,1]])
out = torch.masked_select(x, mask)
print(x)
print(mask) 
print(out)

tensor([[ 1.4176,  1.2236, -1.3988],
        [ 1.2907, -0.0435,  0.0434],
        [ 0.8088, -0.5788,  0.2644]])
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.uint8)
tensor([ 1.4176, -0.0435,  0.2644])


In [29]:
## concatenate arrays 
x = torch.FloatTensor([[1,1,2],[3,3,4]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

print(x, y)


print(z1, z2)

tensor([[1., 1., 2.],
        [3., 3., 4.]]) tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  1.,  2.],
        [ 3.,  3.,  4.],
        [-1., -2., -3.],
        [-4., -5., -6.]]) tensor([[ 1.,  1.,  2., -1., -2., -3.],
        [ 3.,  3.,  4., -4., -5., -6.]])


In [33]:
## Useful math functions

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(torch.add(x1,x2))

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [37]:
## matrix product (m x n) * (n x p) = m x p

x1 = torch.FloatTensor([[1,2,123,143],[94,-12,23,12]])
x2 = torch.FloatTensor([[1,2, 4],[3,4, 6],[4,5, 7],[5,6,8]])

print(torch.mm(x1,x2))

tensor([[1214., 1483., 2021.],
        [ 210.,  327.,  561.]])


In [40]:
## get eigenpair
x1 = torch.FloatTensor([[3,4,5],[9,2,3],[4,9,12]])
print(torch.eig(x1, True))

torch.return_types.eig(
eigenvalues=tensor([[17.8639,  0.0000],
        [-1.7563,  0.0000],
        [ 0.8924,  0.0000]]),
eigenvectors=tensor([[-0.3849, -0.1867, -0.1250],
        [-0.3776,  0.8461, -0.7484],
        [-0.8422, -0.4993,  0.6514]]))


In [41]:
## Autograd

from torch.autograd import Variable

In [42]:
dtype = torch.FloatTensor

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

In [47]:
## random tensors to store inputs and outputs
x = Variable(torch.randn(N, D_in).type(dtype), requires_grad = False)
y = Variable(torch.randn(N, D_out).type(dtype), requires_grad = False)

In [48]:
## store weights as well, with gradients = True
w1 = Variable(torch.randn(D_in, H).type(dtype), requires_grad = True)
w2 = Variable(torch.randn(H, D_out).type(dtype), requires_grad = True)


In [53]:
y

tensor([[ 1.1944e-01, -1.4174e+00,  3.4658e-01, -3.2073e-01,  1.0669e+00,
         -9.6468e-01,  1.7748e-01, -7.3540e-01,  1.5481e+00, -7.0445e-02],
        [ 1.7815e+00, -7.3300e-01,  5.3586e-01,  3.0655e-01,  8.4988e-01,
          4.9805e-01, -1.5253e-01,  2.7163e-02,  1.0626e+00, -1.1011e-01],
        [-7.5116e-02, -1.0352e+00, -1.4129e+00,  7.2949e-01,  5.8510e-01,
          1.1779e+00, -6.3335e-01,  1.3521e+00, -1.0568e+00,  6.7171e-01],
        [ 4.5408e-01,  8.9353e-01, -8.2078e-01, -8.6943e-01, -9.8989e-03,
         -2.3878e-01, -1.1900e+00, -6.9821e-02,  5.8559e-02,  1.8851e-03],
        [-2.1657e+00,  4.6214e-01,  8.7091e-01, -3.7316e-01, -5.4991e-01,
          5.4056e-01, -8.1432e-01, -8.4547e-01, -5.6131e-01, -4.9620e-01],
        [-4.3282e-01, -1.4725e+00, -7.0585e-01, -1.8703e+00,  1.8986e+00,
         -1.7482e+00,  8.7046e-01,  7.4617e-01, -2.8607e+00,  1.9224e+00],
        [-1.1937e+00,  5.3026e-01,  1.2946e+00,  1.4440e+00, -2.0126e-01,
          4.0909e-01,  3.1296e-0

## Compute predictions, then compute backward pass 

In [55]:
## apply gradient descent for each pass, zero the gradients

lr = 1e-6

for t in range(500):
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)
    ## mean squared error
    loss = (y_pred - y).pow(2).sum()
    ## loss: Variable, access the data attribute at [0] to get the loss value itself
#     print(loss.shape)
#     print(t, loss.data)
    
    
    loss.backward()
    
    ## gradient descent on weights
    
    w1.data -= lr*w1.grad.data
    w2.data -= lr*w2.grad.data
    
    ## zero gradients at the end of each pass
    w1.grad.data.zero_()
    w2.grad.data.zero_()

In [57]:
## USE NN MODULE

N, D_in, H, D_out = 64, 1000, 100, 10


In [58]:
## create your Tensors

x = Variable(torch.randn(N, D_in))
y = Variable(torch.randn(N, D_out), requires_grad = False)

In [61]:
## define a sequence of NN layers

model = torch.nn.Sequential(
        torch.nn.Linear(D_in, H),
        torch.nn.ReLU(),
        torch.nn.Linear(H, D_out),)

In [62]:
## use MSE loss, maintain a learning rate

loss_fn = torch.nn.MSELoss(size_average=False)
lr = 1e-5

/Users/pranavbarot/anaconda3/lib/python3.6/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [63]:
## Adam optimizer

optimizer = torch.optim.Adam(model.parameters(), lr = lr)

In [65]:
for t in range(500):
    prediction = model(x)
    
    loss = loss_fn(prediction, y)
    print(t, loss.data)
    
    optimizer.zero_grad()

    # compute gradient of the loss
    loss.backward()

    # .step() makes updates to parameters
    optimizer.step()

0 tensor(627.0806)
1 tensor(625.3212)
2 tensor(623.5674)
3 tensor(621.8196)
4 tensor(620.0769)
5 tensor(618.3381)
6 tensor(616.6071)
7 tensor(614.8820)
8 tensor(613.1605)
9 tensor(611.4423)
10 tensor(609.7308)
11 tensor(608.0257)
12 tensor(606.3244)
13 tensor(604.6281)
14 tensor(602.9346)
15 tensor(601.2472)
16 tensor(599.5682)
17 tensor(597.8940)
18 tensor(596.2255)
19 tensor(594.5634)
20 tensor(592.9061)
21 tensor(591.2512)
22 tensor(589.6031)
23 tensor(587.9610)
24 tensor(586.3224)
25 tensor(584.6867)
26 tensor(583.0562)
27 tensor(581.4301)
28 tensor(579.8110)
29 tensor(578.1954)
30 tensor(576.5833)
31 tensor(574.9758)
32 tensor(573.3716)
33 tensor(571.7711)
34 tensor(570.1763)
35 tensor(568.5849)
36 tensor(566.9983)
37 tensor(565.4188)
38 tensor(563.8448)
39 tensor(562.2779)
40 tensor(560.7144)
41 tensor(559.1555)
42 tensor(557.5999)
43 tensor(556.0539)
44 tensor(554.5126)
45 tensor(552.9736)
46 tensor(551.4387)
47 tensor(549.9110)
48 tensor(548.3915)
49 tensor(546.8780)
50 tensor(

417 tensor(207.8210)
418 tensor(207.2790)
419 tensor(206.7382)
420 tensor(206.1982)
421 tensor(205.6591)
422 tensor(205.1218)
423 tensor(204.5861)
424 tensor(204.0503)
425 tensor(203.5160)
426 tensor(202.9831)
427 tensor(202.4513)
428 tensor(201.9220)
429 tensor(201.3925)
430 tensor(200.8655)
431 tensor(200.3401)
432 tensor(199.8148)
433 tensor(199.2901)
434 tensor(198.7677)
435 tensor(198.2465)
436 tensor(197.7269)
437 tensor(197.2068)
438 tensor(196.6900)
439 tensor(196.1743)
440 tensor(195.6591)
441 tensor(195.1464)
442 tensor(194.6346)
443 tensor(194.1224)
444 tensor(193.6124)
445 tensor(193.1048)
446 tensor(192.5986)
447 tensor(192.0930)
448 tensor(191.5893)
449 tensor(191.0872)
450 tensor(190.5858)
451 tensor(190.0850)
452 tensor(189.5864)
453 tensor(189.0888)
454 tensor(188.5923)
455 tensor(188.0955)
456 tensor(187.6010)
457 tensor(187.1090)
458 tensor(186.6171)
459 tensor(186.1257)
460 tensor(185.6363)
461 tensor(185.1485)
462 tensor(184.6611)
463 tensor(184.1755)
464 tensor(18