## Making PyTorch easy to use: a more intuitive approach to deep learning

### Can do everything in NumPy (nd arrays) but with PyTorch tensors

In [2]:
import torch


In [3]:
## basic operations

x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
x = torch.arange(0,3, step = 0.2)
x

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000])

In [6]:
x = torch.FloatTensor(2, 3)
x

tensor([[1.4013e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [19]:
x = torch.rand(5,3)
out = torch.index_select(x, 0, torch.LongTensor([0,0]))
print(x)

tensor([[0.3603, 0.0832, 0.6640],
        [0.7721, 0.0199, 0.0444],
        [0.2913, 0.9217, 0.9616],
        [0.3593, 0.3893, 0.5650],
        [0.8964, 0.9852, 0.6519]])


In [23]:
## array indexing

x[:,2], x[1:,2]

(tensor([0.6640, 0.0444, 0.9616, 0.5650, 0.6519]),
 tensor([0.0444, 0.9616, 0.5650, 0.6519]))

In [27]:
## selection by masking

x = torch.randn(3,3)
mask = torch.ByteTensor([[1,0,0],[0,1,0], [0,0,1]])
out = torch.masked_select(x, mask)
print(x)
print(mask) 
print(out)

tensor([[ 1.4176,  1.2236, -1.3988],
        [ 1.2907, -0.0435,  0.0434],
        [ 0.8088, -0.5788,  0.2644]])
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.uint8)
tensor([ 1.4176, -0.0435,  0.2644])


In [29]:
## concatenate arrays 
x = torch.FloatTensor([[1,1,2],[3,3,4]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

print(x, y)


print(z1, z2)

tensor([[1., 1., 2.],
        [3., 3., 4.]]) tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  1.,  2.],
        [ 3.,  3.,  4.],
        [-1., -2., -3.],
        [-4., -5., -6.]]) tensor([[ 1.,  1.,  2., -1., -2., -3.],
        [ 3.,  3.,  4., -4., -5., -6.]])


In [33]:
## Useful math functions

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(torch.add(x1,x2))

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [37]:
## matrix product (m x n) * (n x p) = m x p

x1 = torch.FloatTensor([[1,2,123,143],[94,-12,23,12]])
x2 = torch.FloatTensor([[1,2, 4],[3,4, 6],[4,5, 7],[5,6,8]])

print(torch.mm(x1,x2))

tensor([[1214., 1483., 2021.],
        [ 210.,  327.,  561.]])


In [40]:
## get eigenpair
x1 = torch.FloatTensor([[3,4,5],[9,2,3],[4,9,12]])
print(torch.eig(x1, True))

torch.return_types.eig(
eigenvalues=tensor([[17.8639,  0.0000],
        [-1.7563,  0.0000],
        [ 0.8924,  0.0000]]),
eigenvectors=tensor([[-0.3849, -0.1867, -0.1250],
        [-0.3776,  0.8461, -0.7484],
        [-0.8422, -0.4993,  0.6514]]))
